### PR TITLE
Use atnd API in Sinatra app

### PR DESCRIPTION
**Pull request by pocke**
See. http://api.atnd.org/

### CODE REVIEW

**Comment by unasuke** [comment]
That's goooooood!

**Comment by whywaita** [comment]
PRO

**Comment by unasuke** [comment]
ugokanai!!!!!!!!!!!!!!!!

https://twitter.com/yu_suke1994/status/871259913212665856

**Comment by whywaita** [comment]
@unasuke You can try before merge...

**Comment by unasuke** [comment]
@whywaita tadasii(正しい)

**Pull request merged**
